/*
 * Copyright (c) 2026 Fraunhofer IOSB, eine rechtlich nicht selbstaendige
 * Einrichtung der Fraunhofer-Gesellschaft zur Foerderung der angewandten
 * Forschung e.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.fraunhofer.iosb.ilt.dataspace_consumer.simple_converter_extension;

/**
 * Represents a filter used by the simple converter extension.
 *
 * <p>This record holds a filter operation and the corresponding value that the operation will be
 * applied to. The record is immutable and implicitly provides accessor methods {@code operation()}
 * and {@code value()} generated by the compiler.
 *
 * <p>Typical uses are to express simple comparison or matching rules (for example: equals,
 * greater-than, contains) together with the operand that should be compared.
 *
 * @param operation the filter operation to apply (must not be {@code null})
 * @param value the value used by the operation; may be {@code null} depending on the operation
 *     semantics
 */
public record Filter(FilterOperation operation, Object value) {}
