spring:
  application:
    name: dataspace-consumer-framework

# Configuration for the MX-Ports
mx-port: []
  # - name: MX-Port1
  #   execution:
  #     maxGateRequests: 10  # Maximum 10 concurrent gate requests (default: 10)
  #   discovery:
  #     implementation: other.package.DiscoveryImpl
  #     config: {}
  #   accessAndUsageControl:
  #     implementation: other.package.AccessImpl
  #     config: {}
  #   gate:
  #     implementation: other.package.GateImpl
  #     config: {}
  #   converter:
  #     implementation: other.package.ConverterImpl
  #     config: {}
  #   adapter:
  #     implementation: other.package.AdapterImpl
  #     config: {}
  #   trigger:
  #     restHook:
  #       enabled: true
  #     scheduler:
  #       enabled: false
  #       cron: "0 0/5 * * * ?"
  #
  # - name: MX-Port2
  #   execution:
  #     maxGateRequests: 20  # Maximum 20 concurrent gate requests
  #   discovery:
  #     implementation: other.package.DiscoveryImpl
  #     config: {}
  #   accessAndUsageControl:
  #     implementation: other.package.AccessImpl
  #     config: {}
  #   gate:
  #     implementation: other.package.GateImpl
  #     config: {}
  #   converter:
  #     implementation: other.package.ConverterImpl
  #     config: {}
  #   adapter:
  #     implementation: other.package.AdapterImpl
  #     config: {}
  #   trigger:
  #     restHook:
  #       enabled: true
  #     scheduler:
  #       enabled: false
  #       cron: "0 0/5 * * * ?"
