name: Build

on:
  push:
    branches: ["main"]
    paths-ignore: ["**/*.md"]
    tags:
      - "v*.*.*"
      - "parent-v*.*.*"
      - "bom-v*.*.*"
      - "api-v*.*.*"
      - "framework-v*.*.*"
      - "extensions-v*.*.*"
  pull_request:
    branches: ["main"]
    paths-ignore: ["**/*.md"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-parent:
    uses: ./.github/workflows/maven.yml
    permissions:
      contents: write
      actions: read
      packages: write
    with:
      pom-file: "pom.xml"
      # deploy only on main or tag, otherwise install
      maven-phase: ${{ (github.ref_name == 'main' || github.ref_type == 'tag') && 'deploy' || 'install' }}
      maven-args: "-N"

  build-bom:
    needs: [build-parent]
    uses: ./.github/workflows/maven.yml
    permissions:
      contents: write
      actions: read
      packages: write
    with:
      pom-file: "bom/pom.xml"
      # deploy only on main or tag, otherwise install
      maven-phase: ${{ (github.ref_name == 'main' || github.ref_type == 'tag') && 'deploy' || 'install' }}

  build-api:
    needs: [build-parent, build-bom]
    uses: ./.github/workflows/maven.yml
    permissions:
      contents: write
      actions: read
      packages: write
    with:
      pom-file: "api/pom.xml"
      # deploy only on main or tag, otherwise install
      maven-phase: ${{ (github.ref_name == 'main' || github.ref_type == 'tag') && 'deploy' || 'install' }}

  build-framework:
    needs: [build-parent, build-bom, build-api]
    uses: ./.github/workflows/maven.yml
    permissions:
      contents: write
      actions: read
      packages: write
    with:
      pom-file: "framework/pom.xml"
      maven-phase: "package"
      build-artifact-name: framework-artifact
      build-artifact-path: framework/target/

  docker-framework:
    needs: build-framework
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/docker.yml
    with:
      build-artifact-name: framework-artifact
      build-artifact-path: framework/target/
      docker-file-path: ./framework/Dockerfile
      container-image-title: framework
      image-name: ${{ github.repository }}-framework

  build-extensions:
    needs: [build-parent, build-bom, build-api]
    uses: ./.github/workflows/maven.yml
    permissions:
      contents: write
      actions: read
      packages: write
    with:
      pom-file: "extensions/pom.xml"
      maven-phase: "package"
      build-artifact-name: extensions-artifact
      build-artifact-path: extensions/**/target/

  release:
    needs:
      [
        build-parent,
        build-bom,
        build-api,
        build-framework,
        docker-framework,
        build-extensions,
      ]
    if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/release.yml
    permissions:
      contents: write
