name: Build

on:
  push:
    branches: ["main"]
    paths-ignore: ["**/*.md"]
    tags:
      - "v*.*.*"
      - "parent-v*.*.*"
      - "bom-v*.*.*"
      - "api-v*.*.*"
      - "framework-v*.*.*"
      - "extensions-v*.*.*"
  pull_request:
    branches: ["main"]
    paths-ignore: ["**/*.md"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      isTag: ${{ (github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')) && 'true' || 'false' }}
      parent: ${{ (github.ref_name == 'main' || startsWith(github.ref, 'refs/tags/parent-v') || steps.filter.outputs.parent == 'true') && 'true' || 'false' }}
      bom: ${{ (github.ref_name == 'main' || steps.filter.outputs.bom == 'true') && 'true' || 'false' }}
      api: ${{ (github.ref_name == 'main' || steps.filter.outputs.api == 'true') && 'true' || 'false' }}
      framework: ${{ (github.ref_name == 'main' || steps.filter.outputs.framework == 'true') && 'true' || 'false' }}
      extensions: ${{ (github.ref_name == 'main' || steps.filter.outputs.extensions == 'true') && 'true' || 'false' }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: filter
        if: github.ref_type != 'tag' && github.ref_name != 'main'
        with:
          base: ${{ github.base_ref || github.ref }}
          filters: |
            parent:
              - 'pom.xml'
              - 'license-header'
              - '.github/workflows/build.yml'
              - '.github/workflows/maven.yml'
            bom:
              - 'bom/**'
              - '.github/workflows/build.yml'
              - '.github/workflows/maven.yml'
            api:
              - 'api/**'
              - '.github/workflows/build.yml'
              - '.github/workflows/maven.yml'
            framework:
              - 'framework/**'
              - '.github/workflows/build.yml'
              - '.github/workflows/maven.yml'
              - '.github/workflows/docker.yml'
            extensions:
              - 'extensions/**'
              - '.github/workflows/build.yml'
              - '.github/workflows/maven.yml'

  build-parent:
    needs: changes
    if: ${{ needs.changes.outputs.isTag == 'true' || needs.changes.outputs.parent == 'true' }}
    uses: ./.github/workflows/maven.yml
    permissions:
      contents: write
      actions: read
      packages: write
    with:
      pom-file: "pom.xml"
      # deploy only on main or tag, otherwise install
      maven-phase: ${{ (github.ref_name == 'main' || github.ref_type == 'tag') && 'deploy' || 'install' }}
      maven-args: "-N"

  build-bom:
    needs: [changes, build-parent]
    if: |
      always() && !failure() && !cancelled() &&
      (needs.changes.outputs.isTag == 'true' || needs.changes.outputs.bom == 'true' || needs.changes.outputs.parent == 'true')
    uses: ./.github/workflows/maven.yml
    permissions:
      contents: write
      actions: read
      packages: write
    with:
      pom-file: "bom/pom.xml"
      # deploy only on main or tag, otherwise install
      maven-phase: ${{ (github.ref_name == 'main' || github.ref_type == 'tag') && 'deploy' || 'install' }}

  build-api:
    needs: [changes, build-parent, build-bom]
    if: |
      always() && !failure() && !cancelled() &&
      (needs.changes.outputs.isTag == 'true' || needs.changes.outputs.parent == 'true' || needs.changes.outputs.bom == 'true' || needs.changes.outputs.api == 'true')
    uses: ./.github/workflows/maven.yml
    permissions:
      contents: write
      actions: read
      packages: write
    with:
      pom-file: "api/pom.xml"
      # deploy only on main or tag, otherwise install
      maven-phase: ${{ (github.ref_name == 'main' || github.ref_type == 'tag') && 'deploy' || 'install' }}

  build-framework:
    needs: [changes, build-parent, build-bom, build-api]
    if: |
      always() && !failure() && !cancelled() &&
      (needs.changes.outputs.isTag == 'true' || needs.changes.outputs.framework == 'true' || needs.changes.outputs.parent == 'true' || needs.changes.outputs.bom == 'true' || needs.changes.outputs.api == 'true')
    uses: ./.github/workflows/maven.yml
    permissions:
      contents: write
      actions: read
      packages: write
    with:
      pom-file: "framework/pom.xml"
      maven-phase: "package"
      build-artifact-name: framework-artifact
      build-artifact-path: framework/target/

  docker-framework:
    needs: build-framework
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/docker.yml
    with:
      build-artifact-name: framework-artifact
      build-artifact-path: framework/target/
      docker-file-path: ./framework/Dockerfile
      container-image-title: framework
      image-name: ${{ github.repository }}-framework

  build-extensions:
    needs: [changes, build-parent, build-bom, build-api]
    if: |
      always() && !failure() && !cancelled() &&
      (needs.changes.outputs.isTag == 'true' || needs.changes.outputs.extensions == 'true' || needs.changes.outputs.parent == 'true' || needs.changes.outputs.bom == 'true' || needs.changes.outputs.api == 'true')
    uses: ./.github/workflows/maven.yml
    permissions:
      contents: write
      actions: read
      packages: write
    with:
      pom-file: "extensions/pom.xml"
      maven-phase: "package"
      build-artifact-name: extensions-artifact
      build-artifact-path: extensions/**/target/

  release:
    needs:
      [
        changes,
        build-parent,
        build-bom,
        build-api,
        build-framework,
        docker-framework,
        build-extensions,
      ]
    if: needs.changes.outputs.isTag == 'true'
    uses: ./.github/workflows/release.yml
    permissions:
      contents: write
