name: maven.yml
on:
  workflow_call:
    inputs:
      pom-file:
        description: "Path to pom.xml file"
        required: false
        type: string
        default: "pom.xml"
      maven-phase:
        description: "Maven phase to execute"
        required: false
        type: string
        default: "install"
      maven-args:
        description: "Additional Maven arguments"
        required: false
        type: string
      build-artifact-name:
        description: "Name of the build artifact to download"
        required: false
        type: string
      build-artifact-path:
        description: "Path of the build artifact to download"
        required: false
        type: string

permissions:
  contents: read

jobs:
  maven:
    name: Maven Build & Test
    permissions:
      contents: write
      actions: read
      packages: write # write impliziert read
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTOR: ${{ github.actor }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          # Need to access the packages in private repo
          # Remove when repo get public
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN

      - name: Set up Maven Cache
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml', '**/src/**/*.java') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Spotless Check
        run: ./mvnw -f ${{ inputs.pom-file }} -B spotless:check

      - name: Build & test maven project
        run: ./mvnw -f ${{ inputs.pom-file }} -B ${{ inputs.maven-args }} ${{ inputs.maven-phase }}

      - name: Update dependency graph
        if: github.ref_name == 'main'
        uses: advanced-security/maven-dependency-submission-action@v5
        with:
          maven-args: -f ${{ inputs.pom-file }}

      - name: Upload maven build artifacts
        uses: actions/upload-artifact@v7
        if: ${{ inputs.build-artifact-name && inputs.build-artifact-path }}
        with:
          name: ${{ inputs.build-artifact-name }}
          path: ${{ inputs.build-artifact-path }}
          retention-days: 4
