name: release.yml

on:
  workflow_call:

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Download framework artifacts
        uses: actions/download-artifact@v8
        with:
          name: framework-artifact
          path: framework-artifacts/

      - name: Download extensions artifacts
        uses: actions/download-artifact@v8
        with:
          name: extensions-artifact
          path: extensions-artifacts/

      - name: Upload framework JAR to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: framework-artifacts/*.jar
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload extension JARs to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: extensions-artifacts/**/*-all.jar
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
